import albumsData from "@/data/photos.generated.json";

export type Photo = {
  name: string;
  thumb: string;
  full: string;
  width: number;
  height: number;
  blurDataURL: string;
};

export type Album = {
  slug: string;
  title: string;
  location: string | null;
  date: string | null;
  summary: string | null;
  order: number | null;
  cover: Photo;
  photos: Photo[];
};

/** Generated by `scripts/generate-photos.mjs` from the `photos/` directory. */
export const albums = albumsData as Album[];

export function getAlbum(slug: string) {
  return albums.find((album) => album.slug === slug);
}

/** "Bengaluru" + "2023-02" -> "Bengaluru · Feb 2023" */
export function albumMeta(album: Album) {
  const parts: string[] = [];
  if (album.location) parts.push(album.location);
  if (album.date) {
    const date = new Date(`${album.date.length === 7 ? `${album.date}-01` : album.date}T00:00:00Z`);
    if (!Number.isNaN(date.getTime())) {
      parts.push(
        date.toLocaleDateString("en-US", {
          month: "short",
          year: "numeric",
          timeZone: "UTC",
        })
      );
    }
  }
  return parts.join(" · ");
}
