import manifest from "@/data/photos.generated.json";

export type Photo = {
  name: string;
  thumb: string;
  full: string;
  width: number;
  height: number;
  blurDataURL: string;
};

/** A photo shown outside its own album page, so it carries its album back-link. */
export type FeaturedPhoto = Photo & {
  albumSlug: string;
  albumTitle: string;
};

export type Album = {
  slug: string;
  title: string;
  location: string | null;
  date: string | null;
  summary: string | null;
  order: number | null;
  cover: Photo;
  photos: Photo[];
};

type Manifest = {
  albums: Album[];
  /** Photos dropped straight into `photos/`, belonging to no album. */
  singles: Photo[];
  featured: FeaturedPhoto[];
  /** "curated" when photos/featured.json picked them, "latest" when derived. */
  featuredMode: "curated" | "latest";
};

/** Generated by `scripts/generate-photos.mjs` from the `photos/` directory. */
const data = manifest as Manifest;

export const albums = data.albums;
export const singles = data.singles ?? [];
export const featuredMode = data.featuredMode;

/**
 * The individual photographs at the top of /foto: loose frames first, since
 * they are the most recent additions, then the curated picks from albums.
 * Loose frames carry no album, so the lightbox simply omits the album link.
 */
export const frames: (Photo | FeaturedPhoto)[] = [...singles, ...data.featured];

export function getAlbum(slug: string) {
  return albums.find((album) => album.slug === slug);
}

/** "Bengaluru" + "2023-02" -> "Bengaluru · Feb 2023" */
export function albumMeta(album: Album) {
  const parts: string[] = [];
  if (album.location) parts.push(album.location);
  if (album.date) {
    const date = new Date(
      `${album.date.length === 7 ? `${album.date}-01` : album.date}T00:00:00Z`,
    );
    if (!Number.isNaN(date.getTime())) {
      parts.push(
        date.toLocaleDateString("en-US", {
          month: "short",
          year: "numeric",
          timeZone: "UTC",
        }),
      );
    }
  }
  return parts.join(" · ");
}
